/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Sun Aug 23 19:39:18 2015. */

#include "sensordata.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorData_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SensorData, SensorId, SensorId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SensorData, Command, SensorId, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, SensorData, Key, Command, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, SensorData, Value, Key, 0),
    PB_LAST_FIELD
};


